### ISSUE TITLE
DB 의문 사항

### ISSUE THREAD

**Issue by HeeyoonTak** [HeeyoonTak/SKHU_CMS#4]
설계한 DB를 다시 봤는데, files에서 board테이블을 참조하는 외래키가 필요해 보이는데, 어떻게 생각하는지 의견 부탁드립니다.
각 게시판에 올라가는 파일들이 board의 id를 참조해야, 각 게시판 별로 구분해서 업로드한 파일 목록을 확인할 수 있지 않을까? 라는 의문점이 생겼는데...  다른분들은 어떻게 보시나요???

**Comment by yejijang** [comment]
board 테이블에서 files 테이블이랑 board_name 테이블 id 값을 외래키로 가지고 있어서 각 게시판 별로 구분 가능하지 않을까요 ?

**Comment by nsap19** [comment]
게시판 별로 파일들을 모아보는게 필요할까요?? 
그리고 위에서도 말했듯이 이미 board테이블에서 board_name과 files를 모두 참조하기때문에 files에 board테이블 외래키는 없어도 될 것 같아요!

**Comment by HeeyoonTak** [comment]
그렇다면 개발 하면서 문제 생기면 수정하는거로~!!
